defaultBaseImage: docker.io/library/ubuntu
baseImageOverrides:
  github.com/tektoncd/pipeline/cmd/creds-init: gcr.azk8s.cn/tekton-nightly/github.com/tektoncd/pipeline/build-base:latest
  github.com/tektoncd/pipeline/cmd/git-init: gcr.azk8s.cn/tekton-nightly/github.com/tektoncd/pipeline/build-base:latest
  github.com/tektoncd/pipeline/cmd/entrypoint: busybox  # image must have `cp` in $PATH
